# ===============================
# DATABASE CONFIGURATION (MailOS - Prod/Docker)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://10.10.10.50:5432/mailingdb?reWriteBatchedInserts=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:kyntus_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:kyntus_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# 🛡️ THROTTLING (Risk Management - Pour ne pas saturer les connexions)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

# ===============================
# HIBERNATE & JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# LOGS & PERFORMANCE OPTIMIZATION
# ===============================
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=ERROR

# ===============================
# SERVER CONFIGURATION & TIMEOUTS
# ===============================
server.port=${SERVER_PORT:4778}
server.tomcat.connection-timeout=120000
server.tomcat.max-threads=50
server.tomcat.accept-count=100

# ===============================
# MULTIPART / UPLOAD LIMITS
# ===============================
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# ===============================
# ⚡ OMNI SEARCH & JSON FIXES
# ===============================
server.tomcat.max-http-form-post-size=-1
spring.jackson.default-property-inclusion=non_null

# ===============================
# 📧 MAIL CONFIGURATION (IONOS)
# ===============================
spring.mail.host=smtp.ionos.fr
spring.mail.port=587
spring.mail.username=communication.bytel@kyntus.com
spring.mail.password=CJrxPu52h63stCdJa8H6c6p3rhRrNuWt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true